### ISSUE TITLE
Web App Features

### ISSUE THREAD

**Issue by csrordzhn** [ZhongMeiZhou/scraper_webAPP#1]
# Summary of our FB group discussion:
- Nic proposes graphing function for data analysis, as seen here:
  ![2015-11-17 nic_prototype](https://cloud.githubusercontent.com/assets/11346536/11210045/34cfa770-8d60-11e5-8d30-f08a4d6ebff4.jpg)
- Eduardo's proposal is to take that function and use it as part of two major features:
  - **Compare tours in country**: this feature will allow the user to search for a country. The service will return the tour list for that country and will show a bar graph for the tours by price. If the user clicks on a tour, the service should return a line graph with the months and the price variation.
  - **Compare tours by country**: this feature will answer the question "Should I go to X or Y?" by contrasting the costs of tours in country X and country Y in a graph.

The question is: do you agree?

**Comment by bjsalgado** [comment]
For me, Eduardo, subsection a (compare tours in country) sounds better. Most of the travelers already have a bucket list country, so comparing tours by country couldn't be that useful.

**Comment by csrordzhn** [comment]
Agreed on Comparison feature on 2015-11-23 SOA course. UI and views to follow.
