### ISSUE TITLE
Web App Interfaces

### ISSUE THREAD

**Issue by csrordzhn** [ZhongMeiZhou/scraper_webAPP#3]
- Start creating hi-fi interfaces for your web-application 
- Create the TWO interfaces using the Bootstrap framework
- Make sure your interfaces scale/flow between mobile/tablet/desktop

**_NOTE:**_ You may put temporary images or text into your interfaces to have content that you currently do not have data for

**Comment by csrordzhn** [comment]
@nweat  started working on this issue and automated tests from issue #4 . Her work is already merged into master branch.

**Comment by csrordzhn** [comment]
For this hw, nweat work will do but we need to start working on the final UI and avoid rushing by the end of the semester.

**Comment by eduardo-salazar** [comment]
Made changes. I think this could be fe Final layout of the app. Any comments?
